# Generated by Django 3.2.5 on 2021-07-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('about', models.TextField(max_length=400)),
                ('photo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('to_do', models.TextField(max_length=500)),
                ('to_eat', models.TextField(max_length=500)),
                ('to_stay', models.CharField(max_length=500)),
                ('tips', models.CharField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project4_backend_app.user')),
            ],
        ),
    ]
